# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_comment_belong_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belong_to',
        ),
    ]
