# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20170603_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Co',
        ),
        migrations.AddField(
            model_name='comment',
            name='best_comment',
            field=models.BooleanField(default=False),
        ),
    ]
